embed_assets: on

javascripts:
  workspace:
    - public/javascripts/*.js

stylesheets:
  common:
<% if Rails.env == 'production' %>
    - tmp/hassle/stylesheets/*.css
<% else %>
    - public/stylesheets/compiled/*.css
<% end %>
